package subaraki.rpginventory.mod;

import java.util.Arrays;

import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.network.NetworkRegistry;
import net.minecraftforge.fml.relauncher.Side;
import subaraki.rpginventory.capability.RpgInventoryCapability;
import subaraki.rpginventory.handler.GuiHandler;
import subaraki.rpginventory.handler.KeyHandler;
import subaraki.rpginventory.hooks.EventHooks;
import subaraki.rpginventory.item.RpgItems;
import subaraki.rpginventory.network.PacketHandler;
import subaraki.rpginventory.network.PacketOpenRpgInventory;
import subaraki.rpginventory.network.PacketOpenRpgInventory.HandlerOpenRpgInventory;
import subaraki.rpginventory.server.ServerProxy;

@Mod(modid = RpgInventory.MODID, name = RpgInventory.NAME, version = RpgInventory.VERSION)
public class RpgInventory {

	public static final String MODID = "rpginventorymod";
	public static final String NAME = "Rpg Inventory";
	public static final String VERSION = "1.10.2 v1";

	@SidedProxy(clientSide = 
			"subaraki.rpginventory.client.ClientProxy",
			serverSide = 
			"subaraki.rpginventory.server.ServerProxy")
	public static ServerProxy proxy;

	public static RpgInventory INSTANCE;

	@EventHandler 
	public void preInit(FMLPreInitializationEvent event) {

		INSTANCE = this;

		ModMetadata modMeta = event.getModMetadata();
		modMeta.authorList = Arrays.asList(new String[] { "Subaraki" });
		modMeta.autogenerated = false;
		modMeta.credits = "ZetaHunter and Richard Digits (retired team members), Resinesin and Take Weiland for ultra-testing, hints and tips";
		modMeta.description = "Expanded Inventory, Class Armor, and Ultra Fine 3D weapons !";
		modMeta.url = "http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287896-/";

		//inititate networking
		new PacketHandler();

		//always register items in preInit
		RpgItems.init();
		RpgItems.register();
		proxy.registerRenders();

		//Register events, from which registering a capability to the player is one
		MinecraftForge.EVENT_BUS.register(new EventHooks());

		//if(FMLCommonHandler.instance().getSide().isClient())
		MinecraftForge.EVENT_BUS.register(new KeyHandler());

		//register gui handler
		NetworkRegistry.INSTANCE.registerGuiHandler(this, new GuiHandler());

		PacketHandler.NETWORK.registerMessage(HandlerOpenRpgInventory.class, PacketOpenRpgInventory.class, 0, Side.SERVER);
		
		new RpgInventoryCapability().register();
	}

	@EventHandler
	public void init(FMLInitializationEvent event){
		//register colors after preInit
		proxy.registerColors();
	}

	@EventHandler
	public void postInit(FMLPostInitializationEvent event){

	}
}
