package subaraki.rpginventory.mod;

import java.util.Arrays;

import net.minecraft.client.renderer.color.IItemColor;
import net.minecraft.client.renderer.color.ItemColors;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemDye;
import net.minecraft.item.ItemStack;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.registry.GameRegistry;
import subaraki.rpginventory.enums.JewelTypes;
import subaraki.rpginventory.item.RpgInventoryItem;
import subaraki.rpginventory.item.RpgInventoryTab;
import subaraki.rpginventory.item.RpgItems;
import subaraki.rpginventory.mod.server.ServerProxy;

@Mod(modid = RpgInventory.MODID, name = RpgInventory.NAME, version = RpgInventory.VERSION)
public class RpgInventory {

	public static final String MODID = "rpginventorymod";
	public static final String NAME = "Rpg Inventory";
	public static final String VERSION = "1.10.2 v1";

	@SidedProxy(clientSide = 
			"subaraki.rpginventory.mod.client.ClientProxy",
			serverSide = 
			"subaraki.rpginventory.mod.server.ServerProxy")

	public static ServerProxy proxy;
	@EventHandler 
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata modMeta = event.getModMetadata();
		modMeta.authorList = Arrays.asList(new String[] { "Subaraki" });
		modMeta.autogenerated = false;
		modMeta.credits = "ZetaHunter and Richard Digits (retired team members), Resinesin and Take Weiland for ultra-testing, hints and tips";
		modMeta.description = "Expanded Inventory, Class Armor, and Ultra Fine 3D weapons !";
		modMeta.url = "http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287896-/";

		//always register items in preInit
		RpgItems.init();
		RpgItems.register();
		proxy.registerRenders();
	}

	@EventHandler
	public void init(FMLInitializationEvent event){
		
		//register colors after preInit
		proxy.registerColors();
	}
	
	@EventHandler
	public void postInit(FMLPostInitializationEvent event){

	}
}
